### ISSUE TITLE
在使用过程中出现的问题

### ISSUE THREAD

**Issue by YIRU69** [Leonezz/obsidian-tasks-calendar-wrapper#1]
1. 使用插件会自动下载js文件，但是里面包含了两个子文件，这个路径是指向那里？
![image](https://user-images.githubusercontent.com/48148292/219921653-04784f06-9288-4efc-93f8-2f83e486e3cd.png)
图中，我只需要指向这个路径，而不是指向子文件对吧

2. 我如下图中设置，发现并不能运行成功，这是为什么？
![image](https://user-images.githubusercontent.com/48148292/219921684-cf67ef24-08c2-4b1d-a7c0-21a1cda214a1.png)
![image](https://user-images.githubusercontent.com/48148292/219921717-b001bd3b-8916-49db-b5f7-6a9af9dff9ad.png)

希望能帮忙解答一下，我使用原作者的代码是成功了，但是考虑用插件更加方便，谢谢

**Comment by Leonezz** [comment]
感谢使用并反馈！
1. 是的，Script path 指向的是脚本文件的父目录，不需要指向子文件
2. 由于 Filter 字段输入的代码是以字符串的形式传入 dataviewjs 的，因此该代码字符串中的字符串需要特殊处理，即：其中的引号需要转义符。因此，你的设置改为: `dv.pages().file.tasks.where(t => t.tags.includes(\"#task\"))` 应该可以运行。

如果上述解答没有解决你的问题，欢迎进一步讨论。你的反馈对我很有帮助！

**Comment by YIRU69** [comment]
谢谢你的及时回复，确实解决了🎇

**Comment by YIRU69** [comment]
希望你有空可以更新一下使用说明，具体的参数的意义，虽然插件有说明，但是没有编程基础碰到问题确实有点难

**Comment by YIRU69** [comment]
另外请教一下，`dv.pages().file.tasks.where(t => t.tags.includes(\"#task\"))`这个是筛选任务带有task标签的任务吧，如果我该获取所有yaml中tags带有task的文件中所有的任务该怎么做呀，匹配Tasks-plugin的格式
- [ ] ✅test ⏫ 🛫 2023-01-11 📅 2023-01-11

**Comment by YIRU69** [comment]
关于我使用第二的功能，发现出现如下的错误，是什么原因呢？
![image](https://user-images.githubusercontent.com/48148292/219942954-680b8c7a-dc38-4dfa-9d84-dd08d8b15cd7.png)
这是我的设置
![image](https://user-images.githubusercontent.com/48148292/219942975-d4836947-c5a7-49cf-935c-b9e78e423b44.png)

**Comment by YIRU69** [comment]
我发现了一个问题，在日历视图中我点击任务，并没有跳转到相对应的文件，你有这样的bug吗?我使用原作者提供的是可以的

**Comment by Leonezz** [comment]
> 希望你有空可以更新一下使用说明，具体的参数的意义，虽然插件有说明，但是没有编程基础碰到问题确实有点难

目前插件只实现了基础功能，还需要进一步完善，参数部分也是其中之一。目前的参数系统比较适合直接放在 `dataviewjs` 里执行，确实不够友好，后面会重新设计参数接口。

**Comment by Leonezz** [comment]
> 另外请教一下，`dv.pages().file.tasks.where(t => t.tags.includes(\"#task\"))`这个是筛选任务带有task标签的任务吧，如果我该获取所有yaml中tags带有task的文件中所有的任务该怎么做呀，匹配Tasks-plugin的格式
> 
> * [ ]  ✅test ⏫ 🛫 2023-01-11 📅 2023-01-11

匹配所有带有特定 tag 的文件应该可以使用 `dv.pages("#tag")` 筛选。具体的用法有很多，可以参看 `dataviewjs` 的文档： https://blacksmithgu.github.io/obsidian-dataview/api/code-reference/

**Comment by YIRU69** [comment]
> 
可能我的表述有问题，我看原作者是适配Tasks插件的，我也是使用这个插件，我是希望匹配标签有task的文件，而你提供的默认filter是匹配任务中带有task的任务，我需要的是只要这个文件的yaml区有task，我就匹配这个文件的所有任务，当然任务最好要有Task插件的那种格式

**Comment by Leonezz** [comment]
> 关于我使用第二的功能，发现出现如下的错误，是什么原因呢？ ![image](https://user-images.githubusercontent.com/48148292/219942954-680b8c7a-dc38-4dfa-9d84-dd08d8b15cd7.png) 这是我的设置 ![image](https://user-images.githubusercontent.com/48148292/219942975-d4836947-c5a7-49cf-935c-b9e78e423b44.png)

这个问题我尝试复现了一下，应该是你在路径中使用了反斜杠 (\) 的原因，这会使 js 程序认为一部分路径是 8 进制数据而不是字符串，在我的设备上把反斜杠改成斜杠 (/) 可以正常渲染。

**Comment by YIRU69** [comment]
我使用`dv.pages(\"#task\")`报错
![Uploading image.png…]()

**Comment by YIRU69** [comment]
> 这个问题我尝试复现了一下，应该是你在路径中使用了反斜杠 () 的原因，这会使 js 程序认为一部分路径是 8 进制数据而不是字符串，在我的设备上把反斜杠改成斜杠 (/) 可以正常渲染。

这确实如此，我改正过来了，效果没有达成原作者贴图的样子，不知道那里出问题

**Comment by YIRU69** [comment]
![image](https://user-images.githubusercontent.com/48148292/219945541-141cd3cf-fe00-46cd-b079-d80c463403c4.png)

**Comment by Leonezz** [comment]
> ![image](https://user-images.githubusercontent.com/48148292/219945541-141cd3cf-fe00-46cd-b079-d80c463403c4.png)

如果任务没有全部显示，可能是 Filter 部分有错误。如果是样式问题，我也没有搞出贴图那么漂亮的样子。

**Comment by Leonezz** [comment]
> 我发现了一个问题，在日历视图中我点击任务，并没有跳转到相对应的文件，你有这样的bug吗?我使用原作者提供的是可以的

我也有同样的问题，目前还不知道原因。

**Comment by Leonezz** [comment]
https://github.com/Leonezz/obsidian-tasks-calendar-wrapper/issues/1#issuecomment-1435964231

我无法看到图片，可以的话请重新上传。

**Comment by YIRU69** [comment]
![image](https://user-images.githubusercontent.com/48148292/219946037-e3858ed6-52f8-4ef1-a233-50d95d3d54e4.png)

**Comment by Leonezz** [comment]
> ![image](https://user-images.githubusercontent.com/48148292/219946037-e3858ed6-52f8-4ef1-a233-50d95d3d54e4.png)

如果你在 Filter 部分使用 dataviewjs 的 query 语句，就必须保证该语句返回的是 tasks。因为在作者的代码中，对于以 `dv.pages` 开头的输入是直接执行并把返回值设置为 tasks 的：

![image](https://user-images.githubusercontent.com/33564074/219946814-b40ab009-8dce-4f27-9dfb-2594058ebd1d.png)

改成 `dv.pages(\"#task\").file.tasks` 应该可以正常执行。

**Comment by Leonezz** [comment]
> > ![image](https://user-images.githubusercontent.com/48148292/219946037-e3858ed6-52f8-4ef1-a233-50d95d3d54e4.png)
> 
> 如果你在 Filter 部分使用 dataviewjs 的 query 语句，就必须保证该语句返回的是 tasks。因为在作者的代码中，对于以 `dv.pages` 开头的输入是直接执行并把返回值设置为 tasks 的：
> 
> ![image](https://user-images.githubusercontent.com/33564074/219946814-b40ab009-8dce-4f27-9dfb-2594058ebd1d.png)
> 
> 改成 `dv.pages(\"#task\").file.tasks` 应该可以正常执行。

或者也可以输入 `#task` 让它进入最后一个 else 分支

**Comment by YIRU69** [comment]
成功了，谢谢你的解答
