### ISSUE TITLE
[Feature Request] Open pinned and open in sidebar

### ISSUE THREAD

**Issue by pcause** [Leonezz/obsidian-tasks-calendar-wrapper#10]
It would be great to be able to open in the right sidebar.  Full Calendar plugin has this capability and you could see how that plugin does it.  

Make sure timeline always opens in a new tab in the main display.

 Also an option to have the display pinned would be useful.

**Comment by Leonezz** [comment]
This could be a good enhancement!

**Comment by Leonezz** [comment]
This feature would work with the latest release.
