### ISSUE TITLE
[FR] Focus on today should display overdues and recurring tasks

### ISSUE THREAD

**Issue by dr-buhu** [Leonezz/obsidian-tasks-calendar-wrapper#107]
Or this should atleast be an options.
Please...

**Comment by dr-buhu** [comment]
Thanks for adding overdues to focus on today!
Recurring tasks would still be very useful!

**Comment by Leonezz** [comment]
It will be very complicated to fully implement recurence feature in current code base, but I am planning on it in a new implementation of this plugin!
