### ISSUE TITLE
有没有办法跟thino那个在面板上直接点击完成任务而不跳转到文件页面

### ISSUE THREAD

**Issue by lxmwwl** [Leonezz/obsidian-tasks-calendar-wrapper#111]

**Comment by Leonezz** [comment]
目前点击完成任务这个功能是通过调用 Tasks 插件的命令实现的，所以目前应该还是需要打开文件。但后面我打算对这个插件进行重构，使用一套更完善的任务列表组件（https://github.com/Leonezz/tasks-timeline-view），这个组件会自己维护任务的状态，并同步到文件，所以重构后的插件不会再通过其他的插件实现完成任务的功能，也不会打开文件。
