### ISSUE TITLE
sorting order

### ISSUE THREAD

**Issue by pcause** [Leonezz/obsidian-tasks-calendar-wrapper#12]
what is the default sorting order.  the whole lambda stuff is very unclear.  Given what I've seen, it isn't alphabetical based on the text, so what is it.  You might have a base selection for sort order (description, tags, start, due, scheduled, ).  And give a real example of using the lambda to do a few of these.

**Comment by Leonezz** [comment]
The default order is based on the status of the task, which follows the following order:
["overdue", "due", "scheduled", "start", "process", "unplanned", "done", "cancelled"].
In fact I am considering canceling this option cause:
1. It is dangerous to evaluate a user provided lambda.
2. Ordering by status or date time is already reasonable.

**Comment by pcause** [comment]
Allow sorting by text/description.  I start all my items with:

- [ ] HH:MM-HH:MM rest of text

and this lets me have a time based ordering with unplanned at the end.  A second option to sort by dataview formatted start time would be good for many.  So, having a drop down that sorts by:

- text
-  start time (dataview format, ascending)
- tags

and then a second sort (if things equal) by 

- text
-  start time (dataview format, ascending)
-  end time (data view format, ascending)
- tags

**Comment by Leonezz** [comment]
Thanks for the idea, mark as a new feature to be implemented.

**Comment by Leonezz** [comment]
Hi, with the latest release the sorting options are now provided by dropdown selection, includes status, text, start time, due time and tags. New suggestions are still welcomed.

**Comment by pcause** [comment]
than ks.  saw it and great and simpler.
