### ISSUE TITLE
0.3.0 always reports update available

### ISSUE THREAD

**Issue by oschrenk** [Leonezz/obsidian-tasks-calendar-wrapper#123]
Every time I look for available updates, Tasks Calendar Wrapper reports there is one available although I'm on the latest 0.3.0 version.

I believe this is because the `manifest.json` of the 0.3.0 release still reports 0.2.9 

See https://github.com/Leonezz/obsidian-tasks-calendar-wrapper/releases/download/0.3.0/manifest.json

This makes Obsidian think there is an update available.

**Comment by Leonezz** [comment]
I am sorry that I forgot to fix this issue as it was found a long time ago (#116), I am going to fix this right away.

**Comment by oschrenk** [comment]
Ah. Sorry for the double report. 

Closing in favor of #116

**Comment by Leonezz** [comment]
Hi @oschrenk  can you check and tell if this is resolved?

**Comment by oschrenk** [comment]
Looks good. Manifest reports 0.3.1 and Obsidian does not say that there is
an update.
