### ISSUE TITLE
BEST TASK PLUGİN FOR OBSİDİAN

### ISSUE THREAD

**Issue by Medullitus** [Leonezz/obsidian-tasks-calendar-wrapper#124]
THİS İS BEST PLUGİN BUD JUST BEST BUT PLZ DONT LEAVE US WE LOVE U AND UR PLUGİN THX <3<3<3<3 @Leonezz

**Comment by Leonezz** [comment]
Thanks it is very nice of you to say this, I am just been very busy lately and I cannot find that much of time for this project as I did 1 year before, but I am not leaving, I will keep developing this plugin.
I will see what I can do about the time sorting issue you mentioned this weekend, but you need to stop broadcasting it to all the issues.
