### ISSUE TITLE
Clicking on timeline tasks opens the wrong note

### ISSUE THREAD

**Issue by polyipseity** [Leonezz/obsidian-tasks-calendar-wrapper#13]
I think someone submitted an issue to the my repo wrongly (https://github.com/polyipseity/obsidian-terminal/issues/18 and also https://github.com/polyipseity/obsidian-terminal/issues/17), so I am opening this issue for them.

@pcause commented on Apr 4, 2023:
> clicking task on the timeline should open the note containing the task
>
> I have a task that is not from today's daily note. when i click the tasks I get switched to today's daily note instead of the note where the task exists and the popup says it is located. think that you should open the note that the task belongs to.

**Comment by Leonezz** [comment]
Thanks for notifying. These comments are also issued in #6 and #8, maybe there are something wrong with github 😂
