### ISSUE TITLE
Bug? note with more than 1000 lines --> no tasks appear

### ISSUE THREAD

**Issue by danielhofer** [Leonezz/obsidian-tasks-calendar-wrapper#133]
Hi

I'm very happy with the tasks calendar wrapper, but now I encounter a problem, and I think it's because one note is longer than about 1000 lines.

When I delete some lines, tasks appear again. When I have more than 1000 lines, no tasks appear (not even from other and shorter notes).

Is there a chance to fix it?

Thanks
Daniel

**Comment by Leonezz** [comment]
Could your produce a minimal md file that helps to reproduce the issue?

**Comment by danielhofer** [comment]
Unfortunately no. I tried to reproduce it in a new file but I'm not able to. I have several files with about 3000 paragraphs each but there is no problem with your plugin. I'm sorry, it seems to be a problem in my vault.
I solved the problem with splitting the vault.
Thanks.
