### ISSUE TITLE
Support markdown and web links in tasks

### ISSUE THREAD

**Issue by monomolecular** [Leonezz/obsidian-tasks-calendar-wrapper#14]
If I include links in my tasks, which I do all the time they aren't rendered. So I see something like the following...
"Follow up on \[\[Project Name\]\] and read the \[Website\](http://www.website.com)" instead of...
"Followup on [Project Name]() and read the [Website]().

**Comment by Leonezz** [comment]
Thanks for the feedback, this is indeed a problem that needs to be resolved. I will try the HTML `herf` and see how it works.

**Comment by Leonezz** [comment]
With the latest release I believe this feature is working!

**Comment by monomolecular** [comment]
Thank you!

**Comment by monomolecular** [comment]
I looks like there's one scenario that's not handled yet...  [[Test
Task|Testing]]
[image: image.png]

**Comment by Leonezz** [comment]
Yeah the behavior is not the same as the obsidian, I will see what I can do.

**Comment by Leonezz** [comment]
Hi @monomolecular , with the latest version the content is now handed to obsidian api to do the renderring, thus the links should be exactly the same as in note files. How do you like it? Could you please confirm if this issue is solved or not?
