### ISSUE TITLE
Support cancelled tasks

### ISSUE THREAD

**Issue by monomolecular** [Leonezz/obsidian-tasks-calendar-wrapper#15]
Cancelled tasks still show up in the list. I came up with something of a workaround by adding a #cancelled tag and excluding by tag, but I'd like to use the [-] notation built into obsidian-tasks. Thank you!

**Comment by Leonezz** [comment]
Thank you for the feedback, mark this as a feature to be implemented.

**Comment by Leonezz** [comment]
With the latest release, the cancelled tasks are automatically excluded from the view, actually you cannot even have them back. Hope you like it.

**Comment by monomolecular** [comment]
That seems to have done the trick!

**Comment by monomolecular** [comment]
The cancelled tasks seem to have returned.  :(
[image: image.png]

**Comment by Leonezz** [comment]
> 

Sorry but I cannot see the image you provided, could you re-upload it?

**Comment by monomolecular** [comment]
Did that work?

**Comment by Leonezz** [comment]
> Did that work?

Yeah I can see it now.

**Comment by Leonezz** [comment]
I did some digging in this issue and find the reason. I will add on option for cancelled tasks in the next release.

**Comment by Leonezz** [comment]
Hi @monomolecular , in the latest release you can specify arbitrary status of tasks to hide through corresponding status markers list, could you please try it out and confirm if this change resolves the issue ?

**Comment by Leonezz** [comment]
Closing this, please reopen if issue still exists.
