### ISSUE TITLE
Hope to support mobile

### ISSUE THREAD

**Issue by zengkaimin** [Leonezz/obsidian-tasks-calendar-wrapper#17]
Hope to support mobile

**Comment by Leonezz** [comment]
I have no idea how to test on a mobile phone, I will try and see if it works on mobile.

**Comment by Leonezz** [comment]
I have tested on Windows Subsystem for Android, it works fine. Will enable mobile in next release.

**Comment by Leonezz** [comment]
With the latest release the mobile is enabled.
