### ISSUE TITLE
support Custom checkboxes in AnubisNekhet and  Primary theme

### ISSUE THREAD

**Issue by aiyou9** [Leonezz/obsidian-tasks-calendar-wrapper#20]
[Custom checkboxes & Speech bubbles](https://github.com/AnubisNekhet/AnuPpuccin#custom-checkboxes--speech-bubbles)

![](https://github.com/AnubisNekhet/AnuPpuccin/raw/main/assets/gh-checkbox-preview.webp)

 [Alternative Checkboxes](https://github.com/ceciliamay/obsidianmd-theme-primary#-alternative-checkboxes)

**Comment by Leonezz** [comment]
These are beautiful and I would love to have them supported, as discussed in #7 . But I have not figured a good way to support these nice styles, by a good way I mean it needs to fit different themes people are using, and it must update itself when those themes have an update. So basically I cannot just copy the css styles and apply them to this plugin, I need a way to delegate the style of the checkbox in this plugin to the obsidian theme, if you have any idea about how this could be achieved, please do let me know.

**Comment by aiyou9** [comment]
in obsdian tasks plugin, there are some code which can set custom statuses
https://publish.obsidian.md/tasks/Getting+Started/Statuses/Custom+Statuses

https://publish.obsidian.md/tasks/Reference/Status+Collections/About+Status+Collections

**Comment by Leonezz** [comment]
Exactly, and that is why I cannot maintain another set of status in this plugin: it leaves a chance to a conflict.

Here is what I am planning:
1. figure out a way to style the checkboxes with styles of the theme people are using,
2. using Tasks for status change.

**Comment by pcause** [comment]
> Exactly, and that is why I cannot maintain another set of status in this plugin: it leaves a chance to a conflict.
> 
> Here is what I am planning:
> 
>     1. figure out a way to style the checkboxes with styles of the theme people are using,
> 
>     2. using Tasks for status change.

Sounds good.  You can look at the tasks plugin docs where there is an explanation, I think, of the css used for the tasks checkbox and it also supports handling different status characters and theming for them.

**Comment by Leonezz** [comment]
> > Exactly, and that is why I cannot maintain another set of status in this plugin: it leaves a chance to a conflict.
> > Here is what I am planning:
> > ```
> > 1. figure out a way to style the checkboxes with styles of the theme people are using,
> > 
> > 2. using Tasks for status change.
> > ```
> 
> Sounds good. You can look at the tasks plugin docs where there is an explanation, I think, of the css used for the tasks checkbox and it also supports handling different status characters and theming for them.

Yes it is pretty much standard to style checkboxes with the markers as part of the css selector, I am currently working on refactoring the structure of task item component to make it work.

**Comment by Leonezz** [comment]
Hi @aiyou9 , with the latest release I believe the theme defined checkbox styles are now available!

![image](https://github.com/Leonezz/obsidian-tasks-calendar-wrapper/assets/33564074/e10a844b-e243-472c-a84c-cb09de98d56f)

**Comment by aiyou9** [comment]
> Hi @aiyou9 , with the latest release I believe the theme defined checkbox styles are now available!
> 
> ![image](https://user-images.githubusercontent.com/33564074/246467079-e10a844b-e243-472c-a84c-cb09de98d56f.png)

great work, I will test in my ob
