### ISSUE TITLE
New option for entry position. [Top/Today/Bottom]

### ISSUE THREAD

**Issue by Quorafind** [Leonezz/obsidian-tasks-calendar-wrapper#21]
![image](https://github.com/Leonezz/obsidian-tasks-calendar-wrapper/assets/13215013/85b1ad1e-ea9d-4360-9b2a-952a499617fa)

**Comment by Leonezz** [comment]
Because the entry is for "today", so it is placed in today's part.

**Comment by Quorafind** [comment]
Is it possible to make the today's part move to the top?

**Comment by Leonezz** [comment]
You can use enable today focus by clicking the "Today" text, but it will filter all tasks before today out.

If today focus does not meet your needs, maybe I could add an option to explicitly set the entry position.

**Comment by Quorafind** [comment]
I did try it, and also an option should be better. Thanks for your kindness!

**Comment by Leonezz** [comment]
Thank you for your feedback!

**Comment by Leonezz** [comment]
This feature is now available with the latest release.
