### ISSUE TITLE
Support completing tasks like plugin ‘obsidian-checklist-plugin’ and changing tasks status with enhancement issue #7 and #20 

### ISSUE THREAD

**Issue by aiyou9** [Leonezz/obsidian-tasks-calendar-wrapper#23]
if #7 and #20 will be completed with no complex, it may good idea to add a select list of tasks status and support click button to change tasks status of each task in the panel of your plugin [obsidian-tasks-calendar-wrapper](https://github.com/Leonezz/obsidian-tasks-calendar-wrapper)
l knows there is an example of plugin [obsidian-checklist-plugin](https://github.com/delashum/obsidian-checklist-plugin) to complete tasks, 
![image](https://github.com/Leonezz/obsidian-tasks-calendar-wrapper/assets/15712822/48d8f240-f91e-48c2-9f4b-92aa27d7f597)

and if you know some plugins to support change status of tasks like [obsidian-toggle-list](https://github.com/thingnotok/obsidian-toggle-list) , please give me some more.

https://user-images.githubusercontent.com/29173832/221370021-9646a62b-ad31-4212-a850-71919d8a9db7.mov

**Comment by Leonezz** [comment]
Thanks for your feedback!
For status change, you can click the icon on the left of the item to change from todo to completed, vise versa. But I don't quite understand the vidio since this plugin does not provide text editing function.

**Comment by aiyou9** [comment]
> Thanks for your feedback! For status change, you can click the icon on the left of the item to change from todo to completed, vise versa. But I don't quite understand the vidio since this plugin does not provide text editing function.

the video is a example in the Readme of [obsidian-toggle-list](https://github.com/thingnotok/obsidian-toggle-list). And you see all usages in readme of the project

**Comment by Leonezz** [comment]
As what I see, the plugin provides an enhancement for task item editing, specifically, it enhanced the status part of the editing. 

As for a status list, the only way I can think of for now is to add it as a right mouse key context menu to the left icon, and it is a good enhancement.

**Comment by aiyou9** [comment]
> As what I see, the plugin provides an enhancement for task item editing, specifically, it enhanced the status part of the editing.
> 
> As for a status list, the only way I can think of for now is to add it as a right mouse key context menu to the left icon, and it is a good enhancement.
if you mean the icon in next image, let us cheers
![image](https://github.com/Leonezz/obsidian-tasks-calendar-wrapper/assets/15712822/38b97205-ffe0-40e4-ad6c-95a21c2b3e92)

**Comment by Leonezz** [comment]
> > As what I see, the plugin provides an enhancement for task item editing, specifically, it enhanced the status part of the editing.
> > As for a status list, the only way I can think of for now is to add it as a right mouse key context menu to the left icon, and it is a good enhancement.
> > if you mean the icon in next image, let us cheers
> > ![image](https://user-images.githubusercontent.com/15712822/239797062-38b97205-ffe0-40e4-ad6c-95a21c2b3e92.png)

Just to confirm that you are aware, clicking the icon will toggle status between todo and done.
I would really like to work on the document if I got time so that people will know how this plugin works and what functionality it provides :). Too bad I currently have too much to work on and unfortunately it will last for a long time, at least after I got a job.

**Comment by aiyou9** [comment]
> > > 如我所见，该插件为任务项编辑提供了增强功能，具体来说，它增强了编辑的状态部分。
> > > 至于状态列表，目前我能想到的唯一方法是将其作为鼠标右键上下文菜单添加到左侧图标，这是一个很好的增强。
> > > 如果你指的是下一张图片中的图标，让我们欢呼吧
> > > ![图像](https://user-images.githubusercontent.com/15712822/239797062-38b97205-ffe0-40e4-ad6c-95a21c2b3e92.png)
> 
> 只是为了确认您知道，单击该图标将在待办事项和已完成状态之间切换。 如果我有时间，我真的很想处理文档，这样人们就会知道这个插件是如何工作的以及它提供了什么功能:)。太糟糕了，我目前有太多工作要做，不幸的是，它会持续很长时间，至少在我找到工作之后。

I am already write a doc, you can see  [pkmer.cn](https://pkmer.cn/Pkmer-Docs/10-obsidian/obsidian%E7%A4%BE%E5%8C%BA%E6%8F%92%E4%BB%B6/tasks-calendar-wrapper/) and it also a open source doc project for obsidian https://github.com/PKM-er/Pkmer-Docs

**Comment by Leonezz** [comment]
Thanks for your work! It is really great. Can I link this page in the readme or could you make a pr based on this document?
And also thanks for letting me know the site too.

**Comment by aiyou9** [comment]
ok, i may create doc in both english and Chinese to pr but it takes time



| |
***@***.***
|
|
***@***.***
|




---- Replied Message ----
| From | ***@***.***> |
| Date | 05/22/2023 13:24 |
| To | ***@***.***> |
| Cc | Simen ***@***.***>***@***.***> |
| Subject | Re: [Leonezz/obsidian-tasks-calendar-wrapper] Support completing tasks like plugin ‘obsidian-checklist-plugin’ and changing tasks status with enhancement issue #7 and #20  (Issue #23) |

Thanks for your work! It is really great. Can I link this page in the readme or could you make a pr based on this document?
And also thanks for letting me know the site too.

**Comment by aiyou9** [comment]
> 好的，我可能会创建中英文文档到 PR，但这需要时间 | | ***@***.*** | | ***@***.*** |
> [...](#)
> ---- Replied Message ---- | From | ***@***.***> | | Date | 05/22/2023 13:24 | | To | ***@***.***> | | Cc | Simen ***@***.***>***@***.***> | | Subject | Re: [Leonezz/obsidian-tasks-calendar-wrapper] Support completing tasks like plugin ‘obsidian-checklist-plugin’ and changing tasks status with enhancement issue #7 and #20 (Issue #23) | Thanks for your work! It is really great. Can I link this page in the readme or could you make a pr based on this document? And also thanks for letting me know the site too. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***>

sorry for this , I am busy in my work, so I close this issue, but I will update the doc in pkmer.cn for new function

**Comment by Leonezz** [comment]
> > 好的，我可能会创建中英文文档到 PR，但这需要时间 | | _**@**_.*** | | _**@**_.*** |
> > [...](#)
> > ---- Replied Message ---- | From | _**@**_._**> | | Date | 05/22/2023 13:24 | | To | _**@**_.**_> | | Cc | Simen _**@**_._**>**_@_**.**_> | | Subject | Re: [Leonezz/obsidian-tasks-calendar-wrapper] Support completing tasks like plugin ‘obsidian-checklist-plugin’ and changing tasks status with enhancement issue #7 and #20 (Issue #23) | Thanks for your work! It is really great. Can I link this page in the readme or could you make a pr based on this document? And also thanks for letting me know the site too. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: _**@**_.***>
> 
> sorry for this , I am busy in my work, so I close this issue, but I will update the doc in pkmer.cn for new function

No worries at all, the pkmer doc would be a great help too!
