### ISSUE TITLE
mouse is not change to hand style in clicking pencil icon to call tasks modify pan

### ISSUE THREAD

**Issue by aiyou9** [Leonezz/obsidian-tasks-calendar-wrapper#29]
and after click pencil icon, it open page in the same time

![image](https://github.com/Leonezz/obsidian-tasks-calendar-wrapper/assets/15712822/c28d006a-c5f4-47f4-8907-218a7f0717bb)

**Comment by Leonezz** [comment]
The task creat or edit modal should be called out if you have the Tasks plugin installed, otherwise it just open the page.

**Comment by aiyou9** [comment]
> The task creat or edit modal should be called out if you have the Tasks plugin installed, otherwise it just open the page.

yes i know, but if the pencil icon can be click, it may great to change the mouse to hand style to notice user which can be clicked

**Comment by Leonezz** [comment]
You are right, I will change the element type of the pencil icon to the <a></a> tag to make it happen.

**Comment by Leonezz** [comment]
It should be as expected in v0.1.17.
