### ISSUE TITLE
assumption that the 2 items are already installed

### ISSUE THREAD

**Issue by pcause** [Leonezz/obsidian-tasks-calendar-wrapper#3]
It seems there is an assumption that the task-calendar and tasks-timeline are installed, but the README doesn't say that and it doesn't say where (which path, like  /MyVault/MyStuff/SomeFolder) is expected to contain the directories with the code and if one must use the defaultn names for the directories.  Also, where is the generated config file stored?

**Comment by Leonezz** [comment]
This plugin currently uses a re-implementation of the original task-timeline and task-calendar (currently not implemented) scripts with React, so for current and futher versions, the original scripts are not needed to be installed somewhere.

Regarding the config file, the position is upto obsidian, so it should be `.obsidian/plugins/tasks-calendar-wrapper/data.json` by default.

**Comment by pcause** [comment]
thanks.  with the release 0.0.9 the plugin is now showing things.  other issues but will file separate reports.
