### ISSUE TITLE
任务显示问题

### ISSUE THREAD

**Issue by harrylee999** [Leonezz/obsidian-tasks-calendar-wrapper#38]
Thanks to Your Great Work!

目前在使用过程遇到2个问题

1.task不能显示已经done和取消的，设置里面的hide staus我是空的，如图只显示了666
![image](https://github.com/Leonezz/obsidian-tasks-calendar-wrapper/assets/59381501/b54bd363-a672-402c-9561-5231d32ed7e8)

2.点击状态图标自动跳到别的task上，并且把那个任务给勾上，也就是说图标的顺序不对应，比如点666指向了555，这个指向有点随机，有可能是别的任务

![image](https://github.com/Leonezz/obsidian-tasks-calendar-wrapper/assets/59381501/42b460b6-2728-4b6b-8fad-4c467f56056e)

**Comment by harrylee999** [comment]
第一个问题我重启一下就好了，麻烦看看第二个问题

**Comment by Leonezz** [comment]
感谢反馈！我研究一下。

**Comment by Leonezz** [comment]
Hi @harrylee999 , v0.2.2 应该修复了这个问题！

**Comment by harrylee999** [comment]
> 

yeah, 我试了一下，it works!
Thanks！
