### ISSUE TITLE
问题：初次打开ob时列表不显示内容

### ISSUE THREAD

**Issue by xburke** [Leonezz/obsidian-tasks-calendar-wrapper#40]
现象：初次打开ob时列表不显示内容，只有在打开插件设置后，在tasks files框输入任意字符才会刷新出内容，推测是我之前修改过tasks files框的内容之后又删除了导致的

建议：改进刷新逻辑或者增加手动刷新按钮

另外：能否增加仅扫描指定文件夹内md文件的功能（类似Obsidian-Tasks-Calendar的pages筛选）

感谢！

**Comment by Leonezz** [comment]
感谢反馈! 启动 ob 时有几率不触发刷新是个老问题, 目前还不知道什么原因，增加一个手动刷新 ribbon 是个好主意，推荐将打开 view 的命令设置成 ribbon 使用。

限制文件或文件夹是个合理的功能，感谢建议, 会在下个版本中提供！

**Comment by Leonezz** [comment]
启动 OB 内容不加载问题已经找到，会在下个版本中修复!

**Comment by Leonezz** [comment]
0.2.3 版本中这个问题应该不会出现了
