### ISSUE TITLE
Recurring tasks get marked as done, but future task is not created

### ISSUE THREAD

**Issue by Kholdan** [Leonezz/obsidian-tasks-calendar-wrapper#43]
After creating a task with a recurrence, when toggling the state from 'todo' to 'done' from the wrapper, it does not create the next task automatically. If the task is checked in the original note, the future task is created as expected.

In case of conflicts that I may have caused, here is the plugins currently installed, and I have no additional js in this vault at all.
![image](https://github.com/Leonezz/obsidian-tasks-calendar-wrapper/assets/32643844/b60cd0cf-758a-41ae-a8bf-a21203fc8c56)

**Comment by Leonezz** [comment]
Hi @Kholdan thanks for the feedback, unfortunately recurrence is not currently implemented in this plugin. I am still considering how it could be implemented, your suggestion that create a new item when toggling as done could be a solution.

**Comment by Leonezz** [comment]
Hi @Kholdan , with the latest version the recurrence should be working!
