### ISSUE TITLE
[FR] Integrate Eslint into CI with automatically fix and push issues into repo

### ISSUE THREAD

**Issue by Raboro** [Leonezz/obsidian-tasks-calendar-wrapper#44]
You already have a CI for release and a Eslint config file ``.eslintrc``. To have a nice code style you can integrate Eslint, you already configured, into CI. So on every push the code stylings will be checked. Then the build fails and shows you the issues. The problem is that you have to change those issues manuelly. You can improve this by also fixing them in CI via Eslint automatically and push those fixes directly into the repo. 

You need to add:
1. scripts in package.json to call Eslint to fix the issues and validate after that if all issues are gone.
2. fix push and check code styling in CI, first fix then validate
3. Enable GH action bot to push directly via CI into the repo in the Settings: Actions > General  - Workflow permissions - enable read and write.

**Comment by Leonezz** [comment]
Thanks a lot @Raboro for this great suggestion, I would love to integrate these modern Web dev tools in this project! I will learn it when I got time and make it happen!

**Comment by Raboro** [comment]
Thanks for your interest, I can do a PR and add the necessary code to CI (`release.yml`)  and the two scripts (one for fixing issues and one for checking after the fixing) in `package.json` by my own. The only thing I can´t do is enable GH Action bot read and write permissions in the settings. This can only be changed by the owner (you).

**Comment by Leonezz** [comment]
That would be great, I can enable the permissions.

**Comment by Leonezz** [comment]
Actually I just checked, the read and write permissions are already enabled.

**Comment by Raboro** [comment]
I would only run `release.yml` on master branch and create a new `linter.yml` CI file, which does what I am going to add (on every branch). To not trigger deploy on each branch, specially because when I would push on my feature branch, this would trigger deploy, but would fail, because I don´t have the secrets needed to deploy.

**Comment by Leonezz** [comment]
To my knowledge, only new tags pushed would trigger deply action.

**Comment by Raboro** [comment]
So the CI is triggered, if a new tag is pushed:
![image](https://github.com/Leonezz/obsidian-tasks-calendar-wrapper/assets/88288557/59ff876c-080f-467f-8749-cf448a516bdb)

**Comment by Leonezz** [comment]
Yes, to the best of knowledge it is. So I guess you can push your feature branch without triggering deploy.
