### ISSUE TITLE
Feature Request: sort and view time of tasks

### ISSUE THREAD

**Issue by iurobpn** [Leonezz/obsidian-tasks-calendar-wrapper#46]
I would like to have a timeline with the date and time of the current day. I can filter the current day easily, but the sort by start time only seems to sort by date. The idea is to create a timeline of tasks like that:

8:00 breakfast
8:30 work
12:00 lunch
13:00 task x

I have taken a look at the code, but it is way beyond my knowledge of javascript. In dataview js I can accomplish the sorting by doing:

var tasks = dv.pages("").file.tasks;
dv.taskList(tasks.sort(t => t.start),false);

The false parameter just indicates to not group by file, which would sort by start time within the file groups. If this is feasible, it would be a nice feature.

**Comment by Leonezz** [comment]
Hi @iurobpn thanks for the feedback, currently time (hours and minutes) is not supported in this plugin. 

However I found an alternative solution for your needs. That is using the time format as: `HH:MM other text of the item.`, and then you can set the sorting order to text(ascending), and you will get the following view for the examples you provided:

![image](https://github.com/Leonezz/obsidian-tasks-calendar-wrapper/assets/33564074/d1ab2c0a-5f47-4a6a-a4ba-fc6d032778b4)

Hope it helps!

**Comment by iurobpn** [comment]
I think this is the better than viewing with dataview, thank you @Leonezz.

**Comment by Leonezz** [comment]
glad to know it helps!
