### ISSUE TITLE
need an exclude folder list - general comment on folders as well

### ISSUE THREAD

**Issue by pcause** [Leonezz/obsidian-tasks-calendar-wrapper#5]
I have a folder for templates and another for tests and "tasks" from these folders are showing up in "today" in the timeline.  At least can we have an "excluded folder" list added where each folder listed and its children are excluded from the timeline.

More generally, the include is automatically populated.  If one uses daily notes there can be a LOT of  notes listed here.  But you ask for the daily notes folder already.  Why not just an "include list" that can take a folder or note to include beyond the daily notes.

**Comment by Leonezz** [comment]
Thanks for the advice, the automatic populating of `include files` is actually a bug, I will fix it asap.
Also, the folder-based organization is good, I think it will work well in this plugin.

**Comment by Leonezz** [comment]
Hi @pcause , with the new version 0.1.0 released, the excluded folder feature is now added to the options.
