### ISSUE TITLE
Inclusive filter for files/folders to scan for tasks

### ISSUE THREAD

**Issue by BishalTS** [Leonezz/obsidian-tasks-calendar-wrapper#50]
The plugin already has the ability to filter out files/folders using the "Exclude Paths" option. It would be nice also to have an option that does the opposite and only scans the files/folders configured. Like "Include Paths".

**Comment by Leonezz** [comment]
Hi @BishalTS thanks for the contribution ! could you please also make a pr to the documentation (the README.md) so that people would know this useful feature and use it ? it's ok if you dont have time for this, I could also update the doc myself.
