### ISSUE TITLE
clocking on an item doesn't open the note containing the item

### ISSUE THREAD

**Issue by pcause** [Leonezz/obsidian-tasks-calendar-wrapper#6]
When I click on an item it doesn't open the note containing the item.  This is unexpected behavior as one would expect to open the tasks or at note / location where the task is.  Two options:

- the tasks plugin now has an API to open it dialog for editing a task.  Use this or make it an option to use this
- just open the note containing the task and if possible position the cursor/page to the task.

**Comment by Leonezz** [comment]
Hi @pcause , thanks for the report.
Could you please provide more infomation about this unexpected behavior, like where on the item you are clicking?
Cuz the default behavior and the behavior I just tested is opening the file where the item belongs and set the text of the item selected.
Besides, the default behavior of clicking the icon (left of the item) will toggle the status of the item. Could you please try this and see if it is also broken?

**Comment by pcause** [comment]
I have my daily note open and pinned.  when I click it just switches there even though the note shown for the todo is not on the daily note.  an error bubble ops up.  type error this.app.workspace.openlinktext() then is not a funciton.  disappears quickly.  you might consider putting errors on the console as it helps report.

**Comment by Leonezz** [comment]
Thanks for the information, I will figure it out asap.

**Comment by pcause** [comment]
no problem.  take a look at the tasks api for the use of their modal for tasks.  using it will make your stuff even better.  you can add a pencil icon like tasks does to the line and when someone clicks that you call the modal.  if they click the tasks text you show you go to the note.  and if you can detect whether the tasks plugin is installed you can only put that icon on the line if installed.

**Comment by Leonezz** [comment]
That's a good idea! By doing so even editing of task items can also be performed in some extent through this plugin.

**Comment by pcause** [comment]
actually the modal is really good for editing events and since that plugin is so widely used, you could see a lot of users interested. 

btw, I start each of my tasks with:

- [ ] HH:MM-HH:MM the etxt and other stuff

this winds up giving me a day planner like ordering using your plugin.  you might suggest people do that to get a day planner in you README.  That plus the model make you a day planning tool.

**Comment by Leonezz** [comment]
Thank you for the advice, I will organize the meaning and usage of the options and the best practise to the readme when I get the time.

**Comment by Leonezz** [comment]
> no problem. take a look at the tasks api for the use of their modal for tasks. using it will make your stuff even better. you can add a pencil icon like tasks does to the line and when someone clicks that you call the modal. if they click the tasks text you show you go to the note. and if you can detect whether the tasks plugin is installed you can only put that icon on the line if installed.

I checked out the tasks API and found there is no way to provide the context (i.e., the focused task item) to the API while create the task modal, which means the newly created modal will be empty and it doesn't know to which task item the result should go.

I think this makes it unusable since it is meaningless to create an empty modal when clicking an existing task item. And I also tried to call the tasks modal through commands, but I failed to call it out with command `this.app.commands.executeCommandById('obsidian-tasks-plugin:edit-task');`, do you have any idea where the problem might be?

**Comment by Leonezz** [comment]
I figured it out, turns out the command is an `editorCheckCallback`, which requires the active editor and view as parameters.

With the latest release, all task items have a modify icon (pencil emoji), and it should be able to edit task items with modal of tasks plugin when clicked.
