### ISSUE TITLE
failed to display time format

### ISSUE THREAD

**Issue by ForestLH** [Leonezz/obsidian-tasks-calendar-wrapper#60]
This parsing time format seems to have failed
![image](https://github.com/Leonezz/obsidian-tasks-calendar-wrapper/assets/39085999/1032b74a-bffc-4f3a-90a1-5dd724257f4a)
This is my settings. Did I set it wrong?
![image](https://github.com/Leonezz/obsidian-tasks-calendar-wrapper/assets/39085999/04bc03fe-aae3-4de7-91bd-09432ee75873)

**Comment by Leonezz** [comment]
Yes you are using it wrong, the Date Format setting is only for dates. For time you could use the convert24HourTimePrefix option (#57 ). Hope it helps!

**Comment by ForestLH** [comment]
> Yes you are using it wrong, the Date Format setting is only for dates. For time you could use the convert24HourTimePrefix option (#57 ). Hope it helps!

Thank you. It works.I'll close this issue later.
