### ISSUE TITLE
View Completely disappeared

### ISSUE THREAD

**Issue by basikthings** [Leonezz/obsidian-tasks-calendar-wrapper#65]
Not sure what happened, but the tasks view completely disappeared for me. Tried to reinstall it again and that didn't work. Any tips on debugging?

**Comment by basikthings** [comment]
Yep, I tried to rerun from the command line. Here is the log file. 
[obsidian.md-1693381282583.log](https://github.com/Leonezz/obsidian-tasks-calendar-wrapper/files/12473048/obsidian.md-1693381282583.log)

**Comment by basikthings** [comment]
Let me know if you need anything else.

**Comment by Leonezz** [comment]
Sorry but I cannot tell how the disappearing would happen from the log file you provide, actually it seems good. Can you tell is there any errors in you console?

**Comment by basikthings** [comment]
Is there anything else you would recommend as a debugging next step? I really like this plugin and I have no idea why it's not working.

**Comment by basikthings** [comment]
I found the bug, and strange behavior. 

A few things I tried: 
- created a new vault and added tasks and the calendar wrapper plugin and copied my files over. The same issue occured. 
- Then I removed all my files and the issue went away. 
- I then narrowed it down to one of the daily notes that caused the issue. If I deleted that daily note, then the task view came back. 
- I further narrowed it down to a single task that caused the issue. When I deleted it, problem went away. 
- Then I narrowed it down to the date. It turns out that one of my due dates was 2023-11-31, which is not an actual date. I changed it to 2023-11-30 and it worked. That's the bug.

**Comment by Leonezz** [comment]
glad to here it worked! And thanks  for the bug locating,I will try to catch errors like this in the code in the next release.

**Comment by snowgumrd** [comment]
I made exactly the same error (2023-11-31) and had exactly the same result! (view disappeared)  I'm glad I came here looking for answers! Thanks @basikthings !

**Comment by krishaizl** [comment]
I just had the same issue with 2023-11-31 so i would say the bug still exists
