### ISSUE TITLE
The sidebar timeline view cannot be fixed at the bottom half

### ISSUE THREAD

**Issue by MugenLee** [Leonezz/obsidian-tasks-calendar-wrapper#68]
When the sidebar is divided into upper and lower parts, move the task timeline at the bottom, and close the OB, open the OB again, and the task timeline will return to the top

see the  screenshot
![动画5](https://github.com/Leonezz/obsidian-tasks-calendar-wrapper/assets/91043731/c0b06b68-098b-4e97-82df-ffa86facd44c)

**Comment by Leonezz** [comment]
Hi @MugenLee , unfortunately this plugin cannot save and restore the layout, the logic is opening the right reaf and load the view there currently. But this is a good enhancement, I will study the obsidian API about layout and try to implement it in the future version.

**Comment by MugenLee** [comment]
> Hi @MugenLee , unfortunately this plugin cannot save and restore the layout, the logic is opening the right reaf and load the view there currently. But this is a good enhancement, I will study the obsidian API about layout and try to implement it in the future version.

This is a pity. For my scenario, the top of the right sidebar is the calendar and tag list, and the bottom is more suitable for task list.

At the same time, as the plugins I use, many plugins can remember the position where they were finally fixed in the sidebar, such as  the screenshot.

Looking forward to your next update~

**Comment by MugenLee** [comment]
> Hi @MugenLee , unfortunately this plugin cannot save and restore the layout, the logic is opening the right reaf and load the view there currently. But this is a good enhancement, I will study the obsidian API about layout and try to implement it in the future version.

hello, after 3 months of use, I found 2 solutions to this problem, but they both have shortcomings
1. Use Obsidian-Tasks-Timeline
You can pin it to the sidebar like a normal Note, and Obsidian can also remember the location of the sidebar, such as the lower right side. This position is visually comfortable. Every time I open Obsidian it's right there.

But  it is based on the dataview display of  Note, **it will flicker from time to time**, which has a great impact on the experience of editing Note for a long time, so I currently use option 2.

2. Use this plugin  and homepage plugin
After tasks-calendar-wrapper is fixed to the sidebar, you can save the workspace and use the homepage plug-in to automatically call the workspace every time you open Obsidian, so that tasks-calendar-wrapper is on the side every time you open Obsidian. below the bar

But since the workspace is fixed, **it is impossible to remember the note content of the last time Obsidian was closed**, which is a big blow to the continuity of work.

Both solutions are not perfect. We look forward to obsidian-tasks-calendar-wrapper being able to implement the function of fixing it anywhere on Obsidian’s sidebar as soon as possible.

**Comment by Leonezz** [comment]
Hi @MugenLee with efforts of @maoli17 I believe this feature is implemented in v0.3.0!

**Comment by HelloMugen** [comment]
> Hi @MugenLee with efforts of @maoli17 I believe this feature is implemented in v0.3.0!

thanks for work!
