### ISSUE TITLE
when  displaying a todo use the status in the todo

### ISSUE THREAD

**Issue by pcause** [Leonezz/obsidian-tasks-calendar-wrapper#7]
several plugins support enhanced statuses.  By that I mean using:

- [ / ] something in process

or 

- [ >] something delegated

and many others.  when you show a task I think if there is something other than the usual space or X you should show it at the start of the line.

**Comment by pcause** [comment]
tasks already supports the alternative statuses and using css  classes that are supported by several other themes or plugins.  if you use \the same css around the status that tasks uses it should all work.  in your README you can say that you support same css and list the same themes.snippets that tasks support as something a user can use as snippets/themes and that if they already have this enabled in tasks it will show the same in your plugin

**Comment by Leonezz** [comment]
It is a good idea to reuse the css styles implemented by previous works, I will check them out and try to find an elegant way to bring these styles into this plugin.

**Comment by Leonezz** [comment]
Hi @pcause , with the latest release I believe the theme defined checkbox styles are now available!

![image](https://github.com/Leonezz/obsidian-tasks-calendar-wrapper/assets/33564074/e10a844b-e243-472c-a84c-cb09de98d56f)

**Comment by ndharari** [comment]
Hi, a q! Could we have it both ways? Like having the built in style (that shows if the task has started, etc) and if I have some custom one enabled, usa that one

**Comment by Leonezz** [comment]
> 

Hi @ndharari, I believe that could be achieved if you enable the builtin styles and make your custom styles a css snippet, just following the css class names.

**Comment by ndharari** [comment]
Hi! I think I did not explain myself properly. I reallt like how the plugin uses the task metadata to change the checkbox. I was asking if there's any way of keeping that feature for all cases and when I use some custom style, just replace it.

**Comment by ndharari** [comment]
Also there seems to be a problem with the plugin and the "in progress" type of checkboxes. Look in your example above, the in progress and the canceled do not appear on the widget. 
I corroborated this using the example vault also. Only installed task, your plugin minimal and the settings. 
![image](https://github.com/Leonezz/obsidian-tasks-calendar-wrapper/assets/41973171/ad030213-fdf4-46b9-81c8-32a967c91a99)

The "progress bars" are taken from the discord https://discord.com/channels/686053708261228577/744933215063638183/1145481360757244065. 
I dont understand why they dont work:
![image](https://github.com/Leonezz/obsidian-tasks-calendar-wrapper/assets/41973171/a64d94f4-1446-42c3-a6ea-e894bbf5bdf0)

**Comment by ndharari** [comment]
Write me if you prefer a I write a this in a new entry

**Comment by Leonezz** [comment]
> Hi! I think I did not explain myself properly. I reallt like how the plugin uses the task metadata to change the checkbox. I was asking if there's any way of keeping that feature for all cases and when I use some custom style, just replace it.

The builtin style and the theme defined style are conflicted in many cases, so I dont think there is a way to enable both in the same time with all styles working properly.

**Comment by ndharari** [comment]
Done, here https://github.com/Leonezz/obsidian-tasks-calendar-wrapper/issues/66
