### ISSUE TITLE
New task include new line

### ISSUE THREAD

**Issue by elky84** [Leonezz/obsidian-tasks-calendar-wrapper#76]
hello. I am using the plugin very well. Thank you.

When adding a task using New Tasks, an empty blank line is added. Can you make this optional or disable it?

You will understand when you see the image.

thank you

![image](https://github.com/Leonezz/obsidian-tasks-calendar-wrapper/assets/4001940/d506d90c-26c2-4a57-b05b-f92bfd3d3bc2)

![image](https://github.com/Leonezz/obsidian-tasks-calendar-wrapper/assets/4001940/e76b1c6a-7b29-46de-9b2c-b1d9036bee08)

**Comment by Leonezz** [comment]
Hi @elky84 thanks for your feedback and I am glad you find this plugin useful! I understand the issue you are facing and it is a known problem, it will be fixed in the next release but I cannot say when cuz some other thing are taking my time currently, sorry about it.

**Comment by elky84** [comment]
I'll wait! thank you!

**Comment by Leonezz** [comment]
Hi @elky84 , Sorry for not mentioning after the fix, I believe this issue should be resolved in current version,
could you please confirm and close this issue?

**Comment by elky84** [comment]
fix complete. thank you!
