### ISSUE TITLE
plugin do not work...

### ISSUE THREAD

**Issue by wangweitung** [Leonezz/obsidian-tasks-calendar-wrapper#77]
I have plenty todos，the plugin also enabled，but there is no timeline....

any idea what is going wrong？

![图片](https://github.com/Leonezz/obsidian-tasks-calendar-wrapper/assets/8080125/33ff3d3e-b187-4a0f-99d1-c5c060f3fa25)

**Comment by Leonezz** [comment]
Hi @wangweitung , maybe check your todos and see if there is any wrong dates.

**Comment by wangweitung** [comment]
> Hi @wangweitung , maybe check your todos and see if there is any wrong dates.

![image](https://github.com/Leonezz/obsidian-tasks-calendar-wrapper/assets/8080125/371bd458-1b93-4f5f-86c9-7782d46552aa)

**Comment by Leonezz** [comment]
> > Hi @wangweitung , maybe check your todos and see if there is any wrong dates.
> 
> ![image](https://user-images.githubusercontent.com/8080125/281276308-371bd458-1b93-4f5f-86c9-7782d46552aa.png)

Yeah it means there is a wrong date in your todos. A better exception handling will be implemented soon!

**Comment by wangweitung** [comment]
> > > Hi @wangweitung , maybe check your todos and see if there is any wrong dates.
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/8080125/281276308-371bd458-1b93-4f5f-86c9-7782d46552aa.png)
> 
> Yeah it means there is a wrong date in your todos. A better exception handling will be implemented soon!

thanks!

by the way, how could I find the wrong date in my tasks? is there quick way?

**Comment by wangweitung** [comment]
## quick way to find the wrong date here：

```tasks
path includes /
not done
group by date
```

then you will see all the todos below，find the invalid date and then change it.

![image](https://github.com/Leonezz/obsidian-tasks-calendar-wrapper/assets/8080125/2835c791-f9ef-439b-91d3-20c96c1e9505)


it works all  fine now！

thanks for the help！
