### ISSUE TITLE
Opening/Editing Task Failure

### ISSUE THREAD

**Issue by Azurewren** [Leonezz/obsidian-tasks-calendar-wrapper#79]
If I click on a task name to open it's file or modal and I have any file open (including the file that has the task in it), I get the error popup: `Something went wrong: TypeError: this.app.workspace.openLinkText(...).then is not a function`

Looking in the console the full error is:
```
plugin:tasks-calendar-wrapper:36239 Uncaught TypeError: this.app.workspace.openLinkText(...).then is not a function
    at ObsidianBridge.handleCompleteTask (plugin:tasks-calendar-wrapper:36239:47)
    at Object.onToggleTask [as onToggle] (plugin:tasks-calendar-wrapper:35398:19)
    at onClick (plugin:tasks-calendar-wrapper:35531:22)
    at HTMLUnknownElement.callCallback2 (plugin:tasks-calendar-wrapper:15895:22)
    at Object.invokeGuardedCallbackDev (plugin:tasks-calendar-wrapper:15920:24)
    at invokeGuardedCallback (plugin:tasks-calendar-wrapper:15954:39)
    at invokeGuardedCallbackAndCatchFirstError (plugin:tasks-calendar-wrapper:15957:33)
    at executeDispatch (plugin:tasks-calendar-wrapper:19237:11)
    at processDispatchQueueItemsInOrder (plugin:tasks-calendar-wrapper:19257:15)
    at processDispatchQueue (plugin:tasks-calendar-wrapper:19266:13)
handleCompleteTask @ plugin:tasks-calendar-wrapper:36239
onToggleTask @ plugin:tasks-calendar-wrapper:35398
onClick @ plugin:tasks-calendar-wrapper:35531
callCallback2 @ plugin:tasks-calendar-wrapper:15895
invokeGuardedCallbackDev @ plugin:tasks-calendar-wrapper:15920
invokeGuardedCallback @ plugin:tasks-calendar-wrapper:15954
invokeGuardedCallbackAndCatchFirstError @ plugin:tasks-calendar-wrapper:15957
executeDispatch @ plugin:tasks-calendar-wrapper:19237
processDispatchQueueItemsInOrder @ plugin:tasks-calendar-wrapper:19257
processDispatchQueue @ plugin:tasks-calendar-wrapper:19266
dispatchEventsForPlugins @ plugin:tasks-calendar-wrapper:19274
eval @ plugin:tasks-calendar-wrapper:19398
batchedUpdates$1 @ plugin:tasks-calendar-wrapper:31130
batchedUpdates @ plugin:tasks-calendar-wrapper:15800
dispatchEventForPluginEventSystem @ plugin:tasks-calendar-wrapper:19397
dispatchEventWithEnableCapturePhaseSelectiveHydrationWithoutDiscreteEventReplay @ plugin:tasks-calendar-wrapper:17699
dispatchEvent @ plugin:tasks-calendar-wrapper:17693
dispatchDiscreteEvent @ plugin:tasks-calendar-wrapper:17670
```

Further investigation shows that if I have no files open, or a `New tab` opened and in focus, then the clicking works and it opens the task file and/or modal.

Also, clicking the checkbox does not make any changes to the task in its file, but no error popup appears. Also, once again, if I have a New tab page as my focus, then clicking a checkbox makes the appropriate changes in the task's file.

**Comment by Leonezz** [comment]
Hi @Azurewren thanks for the report, but I cannot reproduce the issue you described in my vault. A screen record will help if appropriate.

**Comment by Azurewren** [comment]
I did some more investigation and the clash seems to be coming from the 'No Dupe Leaves' plugin (obsidian://show-plugin?id=no-dupe-leaves or https://github.com/scambier/obsidian-no-dupe-leaves). 

Now that I have identified it, it is obvious as it states in its readme that `Internally, it overwrites the public function openLinkText(), which is called when you click on a link in a note.`

I will turn the other plugin off.. so it has all been resolved and this can be closed with us all more informed than before. :)

**Comment by Leonezz** [comment]
Glad to know!
