### ISSUE TITLE
latest release broke a lot

### ISSUE THREAD

**Issue by pcause** [Leonezz/obsidian-tasks-calendar-wrapper#8]
First, thanks for the integration to the tasks modal.  Works for me other than when I have the pinned pages issue (see below).  When I installed, restarted and opened the calendar the results were not right.

- I had 2 folders in the exclude list.  It now seems to look at the sub-folders which before this release entering an exclude would also exclude the subfolders, which is what I expected.  Need to make it one way or the other but have a way to say to exclude subfolders if the default is only the listed folder.  For example, if /me/test in excluded folders just excludes that flder and not subfolders then /me/test/* should exclude the folder and all subfolders.

- The issue with tasks without any text (just - [ ] )after the task box appearing in the list is back.

-  The issue with the item not opening if there is a pinned tab is there.  here is what the console shows (thanks for adding):

Now the root node are rendering with:  Array(1206)[0 … 99][100 … 199][200 … 299][300 … 399][400 … 499][500 … 599][600 … 699][700 … 799][800 … 899][900 … 999][1000 … 1099][1100 … 1199][1200 … 1205]length: 1206[[Prototype]]: Array(0)

**Comment by pcause** [comment]
i had a plugin called "no dupe leaves'.  disabled and it worked.  so some interaction.  i can live without the no dupe leaves

**Comment by Leonezz** [comment]
Glad to here your issue is solved.
It just came to my mind that for the items of empty "body" (text excluding "- [ ]" and meta data), it is intentionally to display the original text, afterall I cannot display empty. I think it is good to 
reminder people there are empty items in their vault. What do you think about it, is it reasonable to filter empty bodied items out rather than displaying the raw text?

**Comment by pcause** [comment]
the way obsidian works, in live preview, if you enter a task line and then hit enter , a normal behavior, you get a - [ ] automatically inserted on the next line.  so I think many of these are just left there and have no value.  In base editting mode the - [ ] isn't added.  So I think just ignore them and leave them out.

**Comment by Leonezz** [comment]
The best solution might be adding an option, so that the users can make the call.
