### ISSUE TITLE
可否讓插件默認不顯示unplanned task？

### ISSUE THREAD

**Issue by Funyuneun** [Leonezz/obsidian-tasks-calendar-wrapper#86]
您好，非常感謝您製作如此便利好用的插件
只是我會有個困擾，就是我有滿多 task 是不打算設定時間，僅用於紀錄次數等
所以每次打開OB時，都會有一長條unplanned task，直接擠掉今日待辦

我希望能夠在打開OB時，插件可以不顯示unplanned task，除非我去點擊unplanned的篩選按鈕才單獨顯示
或者是默認狀況下，插件會自動激活todo的篩選按鈕，例如圖示：
![image](https://github.com/Leonezz/obsidian-tasks-calendar-wrapper/assets/56835095/6e543450-f79c-4e2b-9f60-bc0c591576a5)

**Comment by Leonezz** [comment]
Hi @Funyuneun , 这个选项应该可以做到在启动时自动激活 todo filter：
![image](https://github.com/Leonezz/obsidian-tasks-calendar-wrapper/assets/33564074/cd595d6e-6efe-4785-9fbd-2d1ee12ff8a0)

**Comment by Funyuneun** [comment]
@Leonezz 謝謝您的回覆，我有將這個選項設為 todo，但重啟 OB 後，還是會將所有的task列出來...
![image](https://github.com/Leonezz/obsidian-tasks-calendar-wrapper/assets/56835095/14630231-7072-45d6-a478-9a7059336387)

![image](https://github.com/Leonezz/obsidian-tasks-calendar-wrapper/assets/56835095/9bfa1c8d-bf64-4f43-aee3-e2a57a294fc7)

**Comment by Leonezz** [comment]
Hi @Funyuneun 谢谢反馈，这应该是个 BUG
