### ISSUE TITLE
BugReport: 设置"Hide Tags"对文件的tags不起作用

### ISSUE THREAD

**Issue by vincentssn** [Leonezz/obsidian-tasks-calendar-wrapper#88]
比如文件A有个tags是project，这个文件A中有个任务的tags是alert，如：
\---
tags:
  \- project
\---
\- [ ] #alert todo xxx
\- [ ] xxx

在设置中对Hide Tags一栏添加tag: #alert 和 #project。
结果在Timeline中，只会隐藏#alert，不会隐藏#project

**Comment by Leonezz** [comment]
感谢反馈！这个问题会在下个版本中修复，但我目前忙于学业论文，可能短时间内不会更新下个版本，非常抱歉。

**Comment by vincentssn** [comment]
> 感谢反馈！这个问题会在下个版本中修复，但我目前忙于学业论文，可能短时间内不会更新下个版本，非常抱歉。

哇！是学生，感谢开源！

**Comment by Leonezz** [comment]
最新的 release 应该修复了这个问题！
