### ISSUE TITLE
BugReport: Quick Entry Panel输入任务后，输入框的内容不会自行清除

### ISSUE THREAD

**Issue by vincentssn** [Leonezz/obsidian-tasks-calendar-wrapper#89]
在Quick Entry Panel输入任务后，点击右侧的↩按钮或者按下回车键后，inbox文件会出现新任务，但Quick Entry Panel的输入框中的任务文本，不会自动清除。需要手动清除。

**Comment by Leonezz** [comment]
这是个问题，我在使用中还存在另一个问题即 Quick Entry Panel 输入后光标消失，不知道你有没有遇到过。

**Comment by vincentssn** [comment]
> 这是个问题，我在使用中还存在另一个问题即 Quick Entry Panel 输入后光标消失，不知道你有没有遇到过。

这点之前倒没留意，刚刚试了下没有复现这个问题
