### ISSUE TITLE
Feedback "NEWS about v1.0" 

### ISSUE THREAD

**Issue by limex** [Leonezz/obsidian-tasks-calendar-wrapper#98]
Hi,
the preview of 1.0 looks great.
Any idea when it is available?

Is there any "buy me a coffee" link? I'd like to donate a coffee or two.
BR Günther

**Comment by SKOHscripts** [comment]
Hello, 
I am a real fan of your obsidian plugin @Leonezz  and your v1.0 teaser is really nice. Is it already available ? I have not found it. Is there the link for donation ?

**Comment by Leonezz** [comment]
> Hello, I am a real fan of your obsidian plugin @Leonezz and your v1.0 teaser is really nice. Is it already available ? I have not found it. Is there the link for donation ?

Working on it, but it seems it is way more complicate to implement it well then I thought when I start the project.
